module.exports={
    //baseUrl:'http://localhost:3000/',
    baseUrl:'http://localhost:3300/',
    signUp:'user',
    login:'users/loginUser',
    signIn:'stud',
    upload:'file',
    attendance:'attendance',
    insertNote:'notes',
    getNews:'news'
};