module.exports={
    //baseUrl:'http://localhost:3000/',
    baseUrl:'http://202.47.116.116:3300/',
    signUp:'user',
    login:'/login',
    signIn:'stud',
    upload:'file',
    attendance:'attendance'
};