module.exports={
    //baseUrl:'http://localhost:3000/',
    baseUrl:'http://localhost:3300/',
    login:'users/loginUser',
    signUp:'users/',
    signIn:'stud',
    upload:'file',
    attendance:'attendance'
};